// apps/frontend/src/features/showcase/products/mock-data.ts
import type { Product, Variant } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod_01",
    reference: "ELEC-001",
    name: "Laptop Pro 15",
    category: "Électronique",
    price: 1299,
    stock: 42,
    status: "ACTIVE",
    description:
      "Laptop haute performance 15 pouces, Core i7, 16 Go RAM, SSD 512 Go.",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "prod_02",
    reference: "ELEC-002",
    name: "Écran 4K 27 pouces",
    category: "Électronique",
    price: 449,
    stock: 18,
    status: "ACTIVE",
    description:
      "Moniteur 4K UHD 27 pouces, 144 Hz, HDR400, temps de réponse 1 ms.",
    createdAt: "2024-01-20T08:30:00Z",
  },
  {
    id: "prod_03",
    reference: "ELEC-003",
    name: "Casque Audio Sans Fil",
    category: "Électronique",
    price: 189,
    stock: 0,
    status: "OUT_OF_STOCK",
    description:
      "Casque Bluetooth 5.0, autonomie 30h, réduction de bruit active.",
    createdAt: "2024-02-01T12:00:00Z",
  },
  {
    id: "prod_04",
    reference: "ELEC-004",
    name: "Clavier Mécanique RGB",
    category: "Électronique",
    price: 129,
    stock: 65,
    status: "ACTIVE",
    description:
      "Clavier mécanique TKL, switches Cherry MX Red, rétroéclairage RGB.",
    similarProductId: "prod_01",
    createdAt: "2024-02-10T09:00:00Z",
  },
  {
    id: "prod_05",
    reference: "VET-001",
    name: "T-shirt Col Rond Premium",
    category: "Vêtements",
    price: 29.99,
    stock: 200,
    status: "ACTIVE",
    description:
      "T-shirt 100% coton biologique, coupe regular, disponible en 5 coloris.",
    createdAt: "2024-02-15T14:00:00Z",
  },
  {
    id: "prod_06",
    reference: "VET-002",
    name: "Jean Slim Stretch",
    category: "Vêtements",
    price: 79.99,
    stock: 150,
    status: "ACTIVE",
    description:
      "Jean slim coupe moderne, tissu stretch 98% coton 2% élasthanne.",
    createdAt: "2024-02-20T11:00:00Z",
  },
  {
    id: "prod_07",
    reference: "VET-003",
    name: "Veste en Cuir",
    category: "Vêtements",
    price: 249,
    stock: 30,
    status: "INACTIVE",
    description: "Veste en cuir véritable, doublure en soie, col mao.",
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "prod_08",
    reference: "VET-004",
    name: "Robe Midi Fleurie",
    category: "Vêtements",
    price: 59.99,
    stock: 0,
    status: "OUT_OF_STOCK",
    description:
      "Robe midi imprimé floral, tissu viscose légère, idéale pour l'été.",
    createdAt: "2024-03-05T09:30:00Z",
  },
  {
    id: "prod_09",
    reference: "ALI-001",
    name: "Café Arabica Bio 500g",
    category: "Alimentation",
    price: 14.99,
    stock: 500,
    status: "ACTIVE",
    description:
      "Café arabica 100% biologique, torréfaction artisanale, notes de chocolat.",
    createdAt: "2024-03-10T08:00:00Z",
  },
  {
    id: "prod_10",
    reference: "ALI-002",
    name: "Huile d'Olive Extra Vierge 1L",
    category: "Alimentation",
    price: 19.99,
    stock: 300,
    status: "INACTIVE",
    description:
      "Huile d'olive première pression à froid, AOP Provence, bouteille en verre.",
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "prod_11",
    reference: "ALI-003",
    name: "Miel de Lavande 250g",
    category: "Alimentation",
    price: 9.99,
    stock: 120,
    status: "DRAFT",
    description:
      "Miel de lavande artisanal, récolte de Provence, pot en verre.",
    createdAt: "2024-03-20T11:00:00Z",
  },
  {
    id: "prod_12",
    reference: "ALI-004",
    name: "Thé Vert Sencha Bio 100g",
    category: "Alimentation",
    price: 11.99,
    stock: 80,
    status: "INACTIVE",
    description:
      "Thé vert japonais Sencha certifié bio, saveur douce et végétale.",
    createdAt: "2024-03-25T12:00:00Z",
  },
  {
    id: "prod_13",
    reference: "MOB-001",
    name: "Bureau Ergonomique Réglable",
    category: "Mobilier",
    price: 599,
    stock: 12,
    status: "ACTIVE",
    description:
      "Bureau assis-debout électrique, plateau 140x70cm, mémorisation 3 hauteurs.",
    createdAt: "2024-04-01T09:00:00Z",
  },
  {
    id: "prod_14",
    reference: "MOB-002",
    name: "Chaise de Bureau Pro",
    category: "Mobilier",
    price: 399,
    stock: 25,
    status: "DRAFT",
    description:
      "Chaise ergonomique lombaire réglable, accoudoirs 4D, tissu respirant.",
    similarProductId: "prod_13",
    createdAt: "2024-04-05T10:00:00Z",
  },
  {
    id: "prod_15",
    reference: "MOB-003",
    name: "Étagère Bibliothèque 5 Niveaux",
    category: "Mobilier",
    price: 149,
    stock: 40,
    status: "DRAFT",
    description:
      "Bibliothèque en bois massif, 5 niveaux ajustables, finition chêne clair.",
    createdAt: "2024-04-10T11:00:00Z",
  },
];

export const INITIAL_VARIANTS: Variant[] = [
  // Laptop Pro 15
  {
    id: "var_01",
    productId: "prod_01",
    name: '15"',
    sku: "LP15-I7-16-512",
    price: 1299,
    stock: 25,
    status: "ACTIVE",
  },
  {
    id: "var_02",
    productId: "prod_01",
    name: '17"',
    sku: "LP17-I7-32-1TB",
    price: 1599,
    stock: 17,
    status: "ACTIVE",
  },
  // Écran 4K
  {
    id: "var_03",
    productId: "prod_02",
    name: '27" Mat',
    sku: "MON27-4K-MAT",
    price: 449,
    stock: 10,
    status: "ACTIVE",
  },
  {
    id: "var_04",
    productId: "prod_02",
    name: '32" Brillant',
    sku: "MON32-4K-GLO",
    price: 549,
    stock: 8,
    status: "ACTIVE",
  },
  // Casque Audio
  {
    id: "var_05",
    productId: "prod_03",
    name: "Noir",
    sku: "HEAD-BLK-BT5",
    price: 189,
    stock: 0,
    status: "INACTIVE",
  },
  {
    id: "var_06",
    productId: "prod_03",
    name: "Blanc",
    sku: "HEAD-WHT-BT5",
    price: 189,
    stock: 0,
    status: "INACTIVE",
  },
  // Clavier
  {
    id: "var_07",
    productId: "prod_04",
    name: "Red Switch",
    sku: "KB-TKL-RED-RGB",
    price: 129,
    stock: 40,
    status: "ACTIVE",
  },
  {
    id: "var_08",
    productId: "prod_04",
    name: "Brown Switch",
    sku: "KB-TKL-BRN-RGB",
    price: 129,
    stock: 25,
    status: "ACTIVE",
  },
  // T-shirt
  {
    id: "var_09",
    productId: "prod_05",
    name: "S",
    sku: "TS-CR-S",
    price: 29.99,
    stock: 60,
    status: "ACTIVE",
  },
  {
    id: "var_10",
    productId: "prod_05",
    name: "M",
    sku: "TS-CR-M",
    price: 29.99,
    stock: 80,
    status: "ACTIVE",
  },
  {
    id: "var_11",
    productId: "prod_05",
    name: "L",
    sku: "TS-CR-L",
    price: 29.99,
    stock: 60,
    status: "ACTIVE",
  },
  // Jean Slim
  {
    id: "var_12",
    productId: "prod_06",
    name: "32/32",
    sku: "JN-SLM-32-32",
    price: 79.99,
    stock: 50,
    status: "ACTIVE",
  },
  {
    id: "var_13",
    productId: "prod_06",
    name: "34/32",
    sku: "JN-SLM-34-32",
    price: 79.99,
    stock: 50,
    status: "ACTIVE",
  },
  {
    id: "var_14",
    productId: "prod_06",
    name: "36/34",
    sku: "JN-SLM-36-34",
    price: 79.99,
    stock: 50,
    status: "ACTIVE",
  },
  // Veste Cuir
  {
    id: "var_15",
    productId: "prod_07",
    name: "M",
    sku: "VJ-LTH-M",
    price: 249,
    stock: 15,
    status: "INACTIVE",
  },
  {
    id: "var_16",
    productId: "prod_07",
    name: "L",
    sku: "VJ-LTH-L",
    price: 249,
    stock: 15,
    status: "INACTIVE",
  },
  // Robe Midi
  {
    id: "var_17",
    productId: "prod_08",
    name: "S",
    sku: "DR-MDI-S",
    price: 59.99,
    stock: 0,
    status: "INACTIVE",
  },
  {
    id: "var_18",
    productId: "prod_08",
    name: "M",
    sku: "DR-MDI-M",
    price: 59.99,
    stock: 0,
    status: "INACTIVE",
  },
  // Café Arabica
  {
    id: "var_19",
    productId: "prod_09",
    name: "Moulu",
    sku: "CF-ARA-GRD",
    price: 14.99,
    stock: 250,
    status: "ACTIVE",
  },
  {
    id: "var_20",
    productId: "prod_09",
    name: "En grains",
    sku: "CF-ARA-BEA",
    price: 14.99,
    stock: 250,
    status: "ACTIVE",
  },
  // Huile d'Olive
  {
    id: "var_21",
    productId: "prod_10",
    name: "1L",
    sku: "OLV-EXV-1L",
    price: 19.99,
    stock: 200,
    status: "ACTIVE",
  },
  {
    id: "var_22",
    productId: "prod_10",
    name: "500ml",
    sku: "OLV-EXV-500",
    price: 11.99,
    stock: 100,
    status: "ACTIVE",
  },
  // Miel
  {
    id: "var_23",
    productId: "prod_11",
    name: "Jar 250g",
    sku: "HON-LAV-250",
    price: 9.99,
    stock: 120,
    status: "ACTIVE",
  },
  {
    id: "var_24",
    productId: "prod_11",
    name: "Jar 500g",
    sku: "HON-LAV-500",
    price: 17.99,
    stock: 0,
    status: "INACTIVE",
  },
  // Thé Vert
  {
    id: "var_25",
    productId: "prod_12",
    name: "Vrac 100g",
    sku: "TEA-SEN-100",
    price: 11.99,
    stock: 80,
    status: "INACTIVE",
  },
  // Bureau
  {
    id: "var_26",
    productId: "prod_13",
    name: "140x70 cm",
    sku: "DSK-ERG-140",
    price: 599,
    stock: 8,
    status: "ACTIVE",
  },
  {
    id: "var_27",
    productId: "prod_13",
    name: "160x80 cm",
    sku: "DSK-ERG-160",
    price: 699,
    stock: 4,
    status: "ACTIVE",
  },
  // Chaise
  {
    id: "var_28",
    productId: "prod_14",
    name: "Tissu Gris",
    sku: "CHR-PRO-GRY",
    price: 399,
    stock: 15,
    status: "ACTIVE",
  },
  {
    id: "var_29",
    productId: "prod_14",
    name: "Tissu Noir",
    sku: "CHR-PRO-BLK",
    price: 399,
    stock: 10,
    status: "ACTIVE",
  },
  // Étagère
  {
    id: "var_30",
    productId: "prod_15",
    name: "Chêne Clair",
    sku: "SHF-5L-OAK",
    price: 149,
    stock: 25,
    status: "ACTIVE",
  },
];
