import { loader } from "fumadocs-core/source";
import type { DocsCollectionEntry } from "fumadocs-mdx/runtime/server";

// .source/index.ts is generated by fumadocs-mdx at build time.
// eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-explicit-any
const { docs } = require("../../.source/index") as {
  docs: DocsCollectionEntry;
};

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
